// Code generated by protoc-gen-go. DO NOT EDIT.
// source: models.proto

/*
Package models is a generated protocol buffer package.

It is generated from these files:
	models.proto

It has these top-level messages:
	User
	Image
	Dialog
	Message
	Vote
	VkAuthRequest
	VkAuthReply
	UserRequest
	UserReply
	RandomRequest
	UsersReply
	VoteRequest
	VoteReply
*/
package models

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_protobuf1 "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Sex int32

const (
	Sex_Woman Sex = 0
	Sex_Man   Sex = 1
)

var Sex_name = map[int32]string{
	0: "Woman",
	1: "Man",
}
var Sex_value = map[string]int32{
	"Woman": 0,
	"Man":   1,
}

func (x Sex) String() string {
	return proto.EnumName(Sex_name, int32(x))
}
func (Sex) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type VoteType int32

const (
	VoteType_none    VoteType = 0
	VoteType_dislike VoteType = 1
	VoteType_like    VoteType = 2
)

var VoteType_name = map[int32]string{
	0: "none",
	1: "dislike",
	2: "like",
}
var VoteType_value = map[string]int32{
	"none":    0,
	"dislike": 1,
	"like":    2,
}

func (x VoteType) String() string {
	return proto.EnumName(VoteType_name, int32(x))
}
func (VoteType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type ObjectType int32

const (
	ObjectType_ObjectNone    ObjectType = 0
	ObjectType_ObjectUser    ObjectType = 1
	ObjectType_ObjectVote    ObjectType = 2
	ObjectType_ObjectMessage ObjectType = 3
)

var ObjectType_name = map[int32]string{
	0: "ObjectNone",
	1: "ObjectUser",
	2: "ObjectVote",
	3: "ObjectMessage",
}
var ObjectType_value = map[string]int32{
	"ObjectNone":    0,
	"ObjectUser":    1,
	"ObjectVote":    2,
	"ObjectMessage": 3,
}

func (x ObjectType) String() string {
	return proto.EnumName(ObjectType_name, int32(x))
}
func (ObjectType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type ErrorCode int32

const (
	ErrorCode_ErrorNone ErrorCode = 0
	ErrorCode_NotFound  ErrorCode = 1
)

var ErrorCode_name = map[int32]string{
	0: "ErrorNone",
	1: "NotFound",
}
var ErrorCode_value = map[string]int32{
	"ErrorNone": 0,
	"NotFound":  1,
}

func (x ErrorCode) String() string {
	return proto.EnumName(ErrorCode_name, int32(x))
}
func (ErrorCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type User struct {
	Id              int64    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	FirstName       string   `protobuf:"bytes,2,opt,name=first_name,json=firstName" json:"first_name,omitempty"`
	LastName        string   `protobuf:"bytes,3,opt,name=last_name,json=lastName" json:"last_name,omitempty"`
	Sex             Sex      `protobuf:"varint,4,opt,name=sex,enum=models.Sex" json:"sex,omitempty"`
	GroupId         int64    `protobuf:"varint,5,opt,name=group_id,json=groupId" json:"group_id,omitempty"`
	Images          []*Image `protobuf:"bytes,6,rep,name=images" json:"images,omitempty"`
	MessagesFromAll bool     `protobuf:"varint,7,opt,name=messages_from_all,json=messagesFromAll" json:"messages_from_all,omitempty"`
	Bio             string   `protobuf:"bytes,8,opt,name=bio" json:"bio,omitempty"`
	Rating          int64    `protobuf:"varint,9,opt,name=rating" json:"rating,omitempty"`
	Age             int64    `protobuf:"varint,10,opt,name=age" json:"age,omitempty"`
	VkId            int64    `protobuf:"varint,11,opt,name=vk_id,json=vkId" json:"vk_id,omitempty"`
	// inject_tag: xorm:"jsonb notnull default '{}' 'created_at'"
	CreatedAt *google_protobuf1.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetSex() Sex {
	if m != nil {
		return m.Sex
	}
	return Sex_Woman
}

func (m *User) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *User) GetImages() []*Image {
	if m != nil {
		return m.Images
	}
	return nil
}

func (m *User) GetMessagesFromAll() bool {
	if m != nil {
		return m.MessagesFromAll
	}
	return false
}

func (m *User) GetBio() string {
	if m != nil {
		return m.Bio
	}
	return ""
}

func (m *User) GetRating() int64 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func (m *User) GetAge() int64 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *User) GetVkId() int64 {
	if m != nil {
		return m.VkId
	}
	return 0
}

func (m *User) GetCreatedAt() *google_protobuf1.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type Image struct {
	Url         string `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	Color       string `protobuf:"bytes,2,opt,name=color" json:"color,omitempty"`
	Hash        string `protobuf:"bytes,3,opt,name=hash" json:"hash,omitempty"`
	HashVersion int64  `protobuf:"varint,4,opt,name=hash_version,json=hashVersion" json:"hash_version,omitempty"`
}

func (m *Image) Reset()                    { *m = Image{} }
func (m *Image) String() string            { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()               {}
func (*Image) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Image) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Image) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

func (m *Image) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Image) GetHashVersion() int64 {
	if m != nil {
		return m.HashVersion
	}
	return 0
}

type Dialog struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *Dialog) Reset()                    { *m = Dialog{} }
func (m *Dialog) String() string            { return proto.CompactTextString(m) }
func (*Dialog) ProtoMessage()               {}
func (*Dialog) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Dialog) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Message struct {
	DialogId string `protobuf:"bytes,1,opt,name=dialog_id,json=dialogId" json:"dialog_id,omitempty"`
	Text     string `protobuf:"bytes,2,opt,name=text" json:"text,omitempty"`
	SenderId int64  `protobuf:"varint,3,opt,name=sender_id,json=senderId" json:"sender_id,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Message) GetDialogId() string {
	if m != nil {
		return m.DialogId
	}
	return ""
}

func (m *Message) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Message) GetSenderId() int64 {
	if m != nil {
		return m.SenderId
	}
	return 0
}

type Vote struct {
	// @inject_tag: storm:"index"
	TargetUserId int64 `protobuf:"varint,1,opt,name=target_user_id,json=targetUserId" json:"target_user_id,omitempty" storm:"index"`
	// @inject_tag: storm:"index"
	VoteType VoteType `protobuf:"varint,2,opt,name=vote_type,json=voteType,enum=models.VoteType" json:"vote_type,omitempty" storm:"index"`
	// @inject_tag: storm:"index"
	VoterId int64 `protobuf:"varint,3,opt,name=voter_id,json=voterId" json:"voter_id,omitempty" storm:"index"`
}

func (m *Vote) Reset()                    { *m = Vote{} }
func (m *Vote) String() string            { return proto.CompactTextString(m) }
func (*Vote) ProtoMessage()               {}
func (*Vote) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Vote) GetTargetUserId() int64 {
	if m != nil {
		return m.TargetUserId
	}
	return 0
}

func (m *Vote) GetVoteType() VoteType {
	if m != nil {
		return m.VoteType
	}
	return VoteType_none
}

func (m *Vote) GetVoterId() int64 {
	if m != nil {
		return m.VoterId
	}
	return 0
}

type VkAuthRequest struct {
	VkToken string `protobuf:"bytes,1,opt,name=vk_token,json=vkToken" json:"vk_token,omitempty"`
}

func (m *VkAuthRequest) Reset()                    { *m = VkAuthRequest{} }
func (m *VkAuthRequest) String() string            { return proto.CompactTextString(m) }
func (*VkAuthRequest) ProtoMessage()               {}
func (*VkAuthRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *VkAuthRequest) GetVkToken() string {
	if m != nil {
		return m.VkToken
	}
	return ""
}

type VkAuthReply struct {
	User  *User  `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	Token string `protobuf:"bytes,3,opt,name=token" json:"token,omitempty"`
}

func (m *VkAuthReply) Reset()                    { *m = VkAuthReply{} }
func (m *VkAuthReply) String() string            { return proto.CompactTextString(m) }
func (*VkAuthReply) ProtoMessage()               {}
func (*VkAuthReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *VkAuthReply) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *VkAuthReply) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type UserRequest struct {
	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
}

func (m *UserRequest) Reset()                    { *m = UserRequest{} }
func (m *UserRequest) String() string            { return proto.CompactTextString(m) }
func (*UserRequest) ProtoMessage()               {}
func (*UserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *UserRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type UserReply struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *UserReply) Reset()                    { *m = UserReply{} }
func (m *UserReply) String() string            { return proto.CompactTextString(m) }
func (*UserReply) ProtoMessage()               {}
func (*UserReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *UserReply) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type RandomRequest struct {
	MinAge int64  `protobuf:"varint,1,opt,name=min_age,json=minAge" json:"min_age,omitempty"`
	MaxAge int64  `protobuf:"varint,2,opt,name=max_age,json=maxAge" json:"max_age,omitempty"`
	Sex    Sex    `protobuf:"varint,3,opt,name=sex,enum=models.Sex" json:"sex,omitempty"`
	Token  string `protobuf:"bytes,4,opt,name=token" json:"token,omitempty"`
}

func (m *RandomRequest) Reset()                    { *m = RandomRequest{} }
func (m *RandomRequest) String() string            { return proto.CompactTextString(m) }
func (*RandomRequest) ProtoMessage()               {}
func (*RandomRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *RandomRequest) GetMinAge() int64 {
	if m != nil {
		return m.MinAge
	}
	return 0
}

func (m *RandomRequest) GetMaxAge() int64 {
	if m != nil {
		return m.MaxAge
	}
	return 0
}

func (m *RandomRequest) GetSex() Sex {
	if m != nil {
		return m.Sex
	}
	return Sex_Woman
}

func (m *RandomRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type UsersReply struct {
	Users []*User `protobuf:"bytes,1,rep,name=users" json:"users,omitempty"`
}

func (m *UsersReply) Reset()                    { *m = UsersReply{} }
func (m *UsersReply) String() string            { return proto.CompactTextString(m) }
func (*UsersReply) ProtoMessage()               {}
func (*UsersReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *UsersReply) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type VoteRequest struct {
	UserId   int64    `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Token    string   `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
	VoteType VoteType `protobuf:"varint,3,opt,name=vote_type,json=voteType,enum=models.VoteType" json:"vote_type,omitempty"`
}

func (m *VoteRequest) Reset()                    { *m = VoteRequest{} }
func (m *VoteRequest) String() string            { return proto.CompactTextString(m) }
func (*VoteRequest) ProtoMessage()               {}
func (*VoteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *VoteRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *VoteRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *VoteRequest) GetVoteType() VoteType {
	if m != nil {
		return m.VoteType
	}
	return VoteType_none
}

type VoteReply struct {
	Matched bool `protobuf:"varint,1,opt,name=matched" json:"matched,omitempty"`
}

func (m *VoteReply) Reset()                    { *m = VoteReply{} }
func (m *VoteReply) String() string            { return proto.CompactTextString(m) }
func (*VoteReply) ProtoMessage()               {}
func (*VoteReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *VoteReply) GetMatched() bool {
	if m != nil {
		return m.Matched
	}
	return false
}

func init() {
	proto.RegisterType((*User)(nil), "models.User")
	proto.RegisterType((*Image)(nil), "models.Image")
	proto.RegisterType((*Dialog)(nil), "models.Dialog")
	proto.RegisterType((*Message)(nil), "models.Message")
	proto.RegisterType((*Vote)(nil), "models.Vote")
	proto.RegisterType((*VkAuthRequest)(nil), "models.VkAuthRequest")
	proto.RegisterType((*VkAuthReply)(nil), "models.VkAuthReply")
	proto.RegisterType((*UserRequest)(nil), "models.UserRequest")
	proto.RegisterType((*UserReply)(nil), "models.UserReply")
	proto.RegisterType((*RandomRequest)(nil), "models.RandomRequest")
	proto.RegisterType((*UsersReply)(nil), "models.UsersReply")
	proto.RegisterType((*VoteRequest)(nil), "models.VoteRequest")
	proto.RegisterType((*VoteReply)(nil), "models.VoteReply")
	proto.RegisterEnum("models.Sex", Sex_name, Sex_value)
	proto.RegisterEnum("models.VoteType", VoteType_name, VoteType_value)
	proto.RegisterEnum("models.ObjectType", ObjectType_name, ObjectType_value)
	proto.RegisterEnum("models.ErrorCode", ErrorCode_name, ErrorCode_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Love service

type LoveClient interface {
	// Sends a greeting
	VkAuth(ctx context.Context, in *VkAuthRequest, opts ...grpc.CallOption) (*VkAuthReply, error)
	// User return user info by their id
	GetUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*User, error)
	// User return list of users
	RandomUsers(ctx context.Context, in *RandomRequest, opts ...grpc.CallOption) (*UsersReply, error)
	// Vote vote for user
	Vote(ctx context.Context, in *VoteRequest, opts ...grpc.CallOption) (*VoteReply, error)
}

type loveClient struct {
	cc *grpc.ClientConn
}

func NewLoveClient(cc *grpc.ClientConn) LoveClient {
	return &loveClient{cc}
}

func (c *loveClient) VkAuth(ctx context.Context, in *VkAuthRequest, opts ...grpc.CallOption) (*VkAuthReply, error) {
	out := new(VkAuthReply)
	err := grpc.Invoke(ctx, "/models.Love/VkAuth", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loveClient) GetUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := grpc.Invoke(ctx, "/models.Love/GetUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loveClient) RandomUsers(ctx context.Context, in *RandomRequest, opts ...grpc.CallOption) (*UsersReply, error) {
	out := new(UsersReply)
	err := grpc.Invoke(ctx, "/models.Love/RandomUsers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loveClient) Vote(ctx context.Context, in *VoteRequest, opts ...grpc.CallOption) (*VoteReply, error) {
	out := new(VoteReply)
	err := grpc.Invoke(ctx, "/models.Love/Vote", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Love service

type LoveServer interface {
	// Sends a greeting
	VkAuth(context.Context, *VkAuthRequest) (*VkAuthReply, error)
	// User return user info by their id
	GetUser(context.Context, *UserRequest) (*User, error)
	// User return list of users
	RandomUsers(context.Context, *RandomRequest) (*UsersReply, error)
	// Vote vote for user
	Vote(context.Context, *VoteRequest) (*VoteReply, error)
}

func RegisterLoveServer(s *grpc.Server, srv LoveServer) {
	s.RegisterService(&_Love_serviceDesc, srv)
}

func _Love_VkAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VkAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoveServer).VkAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.Love/VkAuth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoveServer).VkAuth(ctx, req.(*VkAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Love_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoveServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.Love/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoveServer).GetUser(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Love_RandomUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RandomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoveServer).RandomUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.Love/RandomUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoveServer).RandomUsers(ctx, req.(*RandomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Love_Vote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoveServer).Vote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.Love/Vote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoveServer).Vote(ctx, req.(*VoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Love_serviceDesc = grpc.ServiceDesc{
	ServiceName: "models.Love",
	HandlerType: (*LoveServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VkAuth",
			Handler:    _Love_VkAuth_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _Love_GetUser_Handler,
		},
		{
			MethodName: "RandomUsers",
			Handler:    _Love_RandomUsers_Handler,
		},
		{
			MethodName: "Vote",
			Handler:    _Love_Vote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "models.proto",
}

func init() { proto.RegisterFile("models.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 933 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0x5f, 0x6f, 0xe3, 0x44,
	0x10, 0x3f, 0xdb, 0xf9, 0x63, 0x8f, 0x93, 0x9c, 0xbb, 0x05, 0xea, 0x86, 0x3b, 0x2e, 0x58, 0x77,
	0x28, 0x0a, 0xba, 0x04, 0xc2, 0x13, 0x8f, 0x15, 0xdc, 0xa1, 0x48, 0xb4, 0x27, 0xf9, 0x4a, 0x4f,
	0x3c, 0x59, 0xdb, 0x7a, 0x93, 0x98, 0xd8, 0xde, 0x60, 0xaf, 0xad, 0x54, 0x88, 0x17, 0xbe, 0x02,
	0x1f, 0x0d, 0xf1, 0x0d, 0x78, 0xe3, 0x4b, 0xa0, 0xd9, 0x5d, 0xb7, 0x09, 0xe8, 0x54, 0x9e, 0x32,
	0xf3, 0x9b, 0xd9, 0xdf, 0x6f, 0x76, 0x66, 0xd6, 0x81, 0x5e, 0xc6, 0x63, 0x96, 0x96, 0xd3, 0x6d,
	0xc1, 0x05, 0x27, 0x1d, 0xe5, 0x0d, 0x9f, 0xac, 0x38, 0x5f, 0xa5, 0x6c, 0x46, 0xb7, 0xc9, 0x8c,
	0xe6, 0x39, 0x17, 0x54, 0x24, 0x3c, 0xd7, 0x59, 0xc3, 0x67, 0x3a, 0x2a, 0xbd, 0xeb, 0x6a, 0x39,
	0x13, 0x49, 0xc6, 0x4a, 0x41, 0xb3, 0xad, 0x4a, 0x08, 0xfe, 0x36, 0xa1, 0xf5, 0x43, 0xc9, 0x0a,
	0x32, 0x00, 0x33, 0x89, 0x7d, 0x63, 0x64, 0x8c, 0xad, 0xd0, 0x4c, 0x62, 0xf2, 0x14, 0x60, 0x99,
	0x14, 0xa5, 0x88, 0x72, 0x9a, 0x31, 0xdf, 0x1c, 0x19, 0x63, 0x27, 0x74, 0x24, 0x72, 0x41, 0x33,
	0x46, 0x3e, 0x06, 0x27, 0xa5, 0x4d, 0xd4, 0x92, 0x51, 0x1b, 0x01, 0x19, 0x7c, 0x0a, 0x56, 0xc9,
	0x76, 0x7e, 0x6b, 0x64, 0x8c, 0x07, 0x73, 0x77, 0xaa, 0xeb, 0x7e, 0xcb, 0x76, 0x21, 0xe2, 0xe4,
	0x14, 0xec, 0x55, 0xc1, 0xab, 0x6d, 0x94, 0xc4, 0x7e, 0x5b, 0x0a, 0x76, 0xa5, 0xbf, 0x88, 0xc9,
	0x0b, 0xe8, 0x24, 0x19, 0x5d, 0xb1, 0xd2, 0xef, 0x8c, 0xac, 0xb1, 0x3b, 0xef, 0x37, 0x87, 0x17,
	0x88, 0x86, 0x3a, 0x48, 0x26, 0x70, 0x94, 0xb1, 0xb2, 0x44, 0x3b, 0x5a, 0x16, 0x3c, 0x8b, 0x68,
	0x9a, 0xfa, 0xdd, 0x91, 0x31, 0xb6, 0xc3, 0xc7, 0x4d, 0xe0, 0x75, 0xc1, 0xb3, 0xb3, 0x34, 0x25,
	0x1e, 0x58, 0xd7, 0x09, 0xf7, 0x6d, 0x59, 0x23, 0x9a, 0xe4, 0x23, 0xe8, 0x14, 0x54, 0x24, 0xf9,
	0xca, 0x77, 0xa4, 0xba, 0xf6, 0x30, 0x93, 0xae, 0x98, 0x0f, 0x12, 0x44, 0x93, 0x1c, 0x43, 0xbb,
	0xde, 0x60, 0x99, 0xae, 0xc4, 0x5a, 0xf5, 0x66, 0x11, 0x93, 0xaf, 0x01, 0x6e, 0x0a, 0x46, 0x05,
	0x8b, 0x23, 0x2a, 0xfc, 0xde, 0xc8, 0x18, 0xbb, 0xf3, 0xe1, 0x54, 0x35, 0x7a, 0xda, 0x34, 0x7a,
	0x7a, 0xd9, 0x34, 0x3a, 0x74, 0x74, 0xf6, 0x99, 0x08, 0x96, 0xd0, 0x96, 0x17, 0x41, 0xa9, 0xaa,
	0x48, 0x65, 0xbb, 0x9d, 0x10, 0x4d, 0xf2, 0x01, 0xb4, 0x6f, 0x78, 0xca, 0x0b, 0xdd, 0x6a, 0xe5,
	0x10, 0x02, 0xad, 0x35, 0x2d, 0xd7, 0xba, 0xc3, 0xd2, 0x26, 0x9f, 0x42, 0x0f, 0x7f, 0xa3, 0x9a,
	0x15, 0x65, 0xc2, 0x73, 0xd9, 0x66, 0x2b, 0x74, 0x11, 0xbb, 0x52, 0x50, 0xe0, 0x43, 0xe7, 0xdb,
	0x84, 0xa6, 0x7c, 0xb5, 0x37, 0x56, 0x07, 0xc7, 0x1a, 0xbc, 0x83, 0xee, 0xb9, 0x6a, 0x10, 0x8e,
	0x30, 0x96, 0x49, 0xd1, 0x5d, 0x86, 0xad, 0x80, 0x45, 0x8c, 0xc2, 0x82, 0xed, 0x84, 0xae, 0x46,
	0xda, 0x78, 0xa0, 0x64, 0x79, 0xcc, 0x0a, 0x3c, 0x60, 0x49, 0x55, 0x5b, 0x01, 0x8b, 0x38, 0xa8,
	0xa1, 0x75, 0xc5, 0x05, 0x23, 0xcf, 0x61, 0x20, 0x68, 0xb1, 0x62, 0x22, 0xaa, 0x4a, 0x95, 0xa9,
	0x76, 0xaa, 0xa7, 0x50, 0xdc, 0xb5, 0x45, 0x4c, 0x5e, 0x82, 0x53, 0x73, 0xc1, 0x22, 0x71, 0xbb,
	0x55, 0xcb, 0x35, 0x98, 0x7b, 0xcd, 0xa8, 0x91, 0xe6, 0xf2, 0x76, 0xcb, 0x42, 0xbb, 0xd6, 0x16,
	0x6e, 0x0c, 0xda, 0x7b, 0xc2, 0x5d, 0xe9, 0x2f, 0xe2, 0x60, 0x02, 0xfd, 0xab, 0xcd, 0x59, 0x25,
	0xd6, 0x21, 0xfb, 0xb9, 0x62, 0xa5, 0x90, 0xb9, 0x9b, 0x48, 0xf0, 0x0d, 0xcb, 0xf5, 0xad, 0xba,
	0xf5, 0xe6, 0x12, 0xdd, 0xe0, 0x15, 0xb8, 0x4d, 0xee, 0x36, 0xbd, 0x25, 0x23, 0x68, 0x61, 0x8d,
	0x32, 0xcb, 0x9d, 0xf7, 0x1a, 0x7d, 0x2c, 0x31, 0x94, 0x11, 0x1c, 0x8a, 0x22, 0x52, 0xfd, 0x57,
	0x4e, 0xf0, 0x19, 0xb8, 0x32, 0x47, 0x0b, 0x9e, 0x40, 0xf7, 0xf0, 0xaa, 0x9d, 0x4a, 0x5e, 0x32,
	0x78, 0x09, 0x8e, 0xca, 0xfb, 0x5f, 0x62, 0x41, 0x0d, 0xfd, 0x90, 0xe6, 0x31, 0xcf, 0xf6, 0x88,
	0xb3, 0x24, 0x8f, 0x70, 0x27, 0x35, 0x71, 0x96, 0xe4, 0x67, 0x2b, 0x26, 0x03, 0x74, 0x27, 0x03,
	0xa6, 0x0e, 0xd0, 0x1d, 0x06, 0xf4, 0xc3, 0xb3, 0xde, 0xf3, 0xf0, 0xee, 0xae, 0xd3, 0xda, 0xbf,
	0xce, 0x17, 0x00, 0x58, 0x45, 0xa9, 0xea, 0x0c, 0xa0, 0x8d, 0xd5, 0x94, 0xbe, 0x21, 0x1f, 0xe0,
	0x61, 0xa1, 0x2a, 0x14, 0x6c, 0xc0, 0xc5, 0x21, 0x3d, 0xd4, 0x80, 0x7b, 0x3d, 0x73, 0x4f, 0xef,
	0x70, 0xf6, 0xd6, 0x43, 0xb3, 0x0f, 0x5e, 0x80, 0xa3, 0xc4, 0xb0, 0x3a, 0x1f, 0x6f, 0x2e, 0x6e,
	0xd6, 0x4c, 0x49, 0xd9, 0x61, 0xe3, 0x4e, 0x4e, 0xc1, 0x7a, 0xcb, 0x76, 0xc4, 0x81, 0xf6, 0x3b,
	0x9e, 0xd1, 0xdc, 0x7b, 0x44, 0xba, 0x60, 0x9d, 0xd3, 0xdc, 0x33, 0x26, 0x9f, 0x83, 0xdd, 0xf0,
	0x12, 0x1b, 0x5a, 0x39, 0xcf, 0x99, 0xf7, 0x88, 0xb8, 0xd0, 0x8d, 0x93, 0x32, 0x4d, 0x36, 0xcc,
	0x33, 0x10, 0x96, 0x96, 0x39, 0x79, 0x03, 0xf0, 0xe6, 0xfa, 0x27, 0x76, 0x23, 0x64, 0xfa, 0xa0,
	0xf1, 0x2e, 0xd4, 0xa1, 0x3b, 0x1f, 0xdb, 0xe1, 0x19, 0xf7, 0x3e, 0x0a, 0x78, 0x26, 0x39, 0x82,
	0xbe, 0xf2, 0xf5, 0x23, 0xf3, 0xac, 0xc9, 0x18, 0x9c, 0x57, 0x45, 0xc1, 0x8b, 0x6f, 0x78, 0xcc,
	0x48, 0x5f, 0x3b, 0x9a, 0xae, 0x07, 0xf6, 0x05, 0x17, 0xaf, 0x79, 0x95, 0xc7, 0x9e, 0x31, 0xff,
	0xd3, 0x84, 0xd6, 0xf7, 0xbc, 0x66, 0xe4, 0x1c, 0x3a, 0x6a, 0x4f, 0xc9, 0x87, 0x77, 0x8d, 0xd9,
	0xdf, 0xf1, 0xe1, 0xf1, 0xbf, 0xe1, 0x6d, 0x7a, 0x1b, 0x9c, 0xfc, 0xf6, 0xc7, 0x5f, 0xbf, 0x9b,
	0x47, 0xe4, 0xb1, 0xfc, 0x2f, 0xa8, 0xbf, 0x9c, 0xd1, 0x4a, 0xac, 0x67, 0xf5, 0x86, 0x9c, 0x43,
	0xf7, 0x3b, 0xf5, 0xf2, 0xc8, 0xf1, 0xc1, 0x38, 0x35, 0xdb, 0xc1, 0x8c, 0x83, 0x67, 0x92, 0xe6,
	0x94, 0x9c, 0x34, 0x34, 0x72, 0xe6, 0xb3, 0x5f, 0xf4, 0x88, 0x7f, 0x25, 0x3f, 0x82, 0xab, 0xf6,
	0x54, 0x6e, 0xcd, 0x7d, 0x89, 0x07, 0xcb, 0x3b, 0x24, 0xfb, 0xa4, 0x6a, 0xb7, 0xfe, 0x4b, 0x5d,
	0x73, 0xfc, 0xf0, 0xe2, 0xbf, 0xd3, 0x32, 0x49, 0x59, 0x49, 0x2e, 0xf5, 0x47, 0xe4, 0x78, 0x7f,
	0x1f, 0x1a, 0xc6, 0xa3, 0x43, 0x10, 0x09, 0x9f, 0x4b, 0xc2, 0x4f, 0x82, 0x27, 0xef, 0xa9, 0x15,
	0x05, 0xd8, 0x75, 0x47, 0x7e, 0x94, 0xbf, 0xfa, 0x27, 0x00, 0x00, 0xff, 0xff, 0x17, 0x67, 0x8d,
	0xfa, 0x41, 0x07, 0x00, 0x00,
}
