// Code generated by protoc-gen-go. DO NOT EDIT.
// source: models.proto

/*
Package models is a generated protocol buffer package.

It is generated from these files:
	models.proto

It has these top-level messages:
	TrainingDirection
	Group
	User
	Image
	Dialog
	Message
	Vote
	VkAuthRequest
	VkAuthReply
	UserRequest
	UserReply
	RandomRequest
	UsersReply
	VoteRequest
	VoteReply
*/
package models

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_protobuf1 "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Sex int32

const (
	Sex_Woman Sex = 0
	Sex_Man   Sex = 1
)

var Sex_name = map[int32]string{
	0: "Woman",
	1: "Man",
}
var Sex_value = map[string]int32{
	"Woman": 0,
	"Man":   1,
}

func (x Sex) String() string {
	return proto.EnumName(Sex_name, int32(x))
}
func (Sex) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Faculty int32

const (
	Faculty_faculty_none Faculty = 0
	Faculty_FMF          Faculty = 1
	Faculty_EGF          Faculty = 2
	Faculty_FIP          Faculty = 3
	Faculty_FF           Faculty = 4
	Faculty_HGF          Faculty = 5
	Faculty_FU           Faculty = 6
)

var Faculty_name = map[int32]string{
	0: "faculty_none",
	1: "FMF",
	2: "EGF",
	3: "FIP",
	4: "FF",
	5: "HGF",
	6: "FU",
}
var Faculty_value = map[string]int32{
	"faculty_none": 0,
	"FMF":          1,
	"EGF":          2,
	"FIP":          3,
	"FF":           4,
	"HGF":          5,
	"FU":           6,
}

func (x Faculty) String() string {
	return proto.EnumName(Faculty_name, int32(x))
}
func (Faculty) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type VoteType int32

const (
	VoteType_vote_none VoteType = 0
	VoteType_dislike   VoteType = 1
	VoteType_like      VoteType = 2
)

var VoteType_name = map[int32]string{
	0: "vote_none",
	1: "dislike",
	2: "like",
}
var VoteType_value = map[string]int32{
	"vote_none": 0,
	"dislike":   1,
	"like":      2,
}

func (x VoteType) String() string {
	return proto.EnumName(VoteType_name, int32(x))
}
func (VoteType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type ObjectType int32

const (
	ObjectType_ObjectNone    ObjectType = 0
	ObjectType_ObjectUser    ObjectType = 1
	ObjectType_ObjectVote    ObjectType = 2
	ObjectType_ObjectMessage ObjectType = 3
)

var ObjectType_name = map[int32]string{
	0: "ObjectNone",
	1: "ObjectUser",
	2: "ObjectVote",
	3: "ObjectMessage",
}
var ObjectType_value = map[string]int32{
	"ObjectNone":    0,
	"ObjectUser":    1,
	"ObjectVote":    2,
	"ObjectMessage": 3,
}

func (x ObjectType) String() string {
	return proto.EnumName(ObjectType_name, int32(x))
}
func (ObjectType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type ErrorCode int32

const (
	ErrorCode_ErrorNone ErrorCode = 0
	ErrorCode_NotFound  ErrorCode = 1
)

var ErrorCode_name = map[int32]string{
	0: "ErrorNone",
	1: "NotFound",
}
var ErrorCode_value = map[string]int32{
	"ErrorNone": 0,
	"NotFound":  1,
}

func (x ErrorCode) String() string {
	return proto.EnumName(ErrorCode_name, int32(x))
}
func (ErrorCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type TrainingDirection struct {
	Id                int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Title             string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	ShortNameTemplate string `protobuf:"bytes,3,opt,name=short_name_template,json=shortNameTemplate" json:"short_name_template,omitempty"`
}

func (m *TrainingDirection) Reset()                    { *m = TrainingDirection{} }
func (m *TrainingDirection) String() string            { return proto.CompactTextString(m) }
func (*TrainingDirection) ProtoMessage()               {}
func (*TrainingDirection) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TrainingDirection) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TrainingDirection) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *TrainingDirection) GetShortNameTemplate() string {
	if m != nil {
		return m.ShortNameTemplate
	}
	return ""
}

type Group struct {
	Id                int64   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Faculty           Faculty `protobuf:"varint,2,opt,name=faculty,enum=models.Faculty" json:"faculty,omitempty"`
	StartYear         int64   `protobuf:"varint,3,opt,name=start_year,json=startYear" json:"start_year,omitempty"`
	TrainingDirection int64   `protobuf:"varint,4,opt,name=training_direction,json=trainingDirection" json:"training_direction,omitempty"`
}

func (m *Group) Reset()                    { *m = Group{} }
func (m *Group) String() string            { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()               {}
func (*Group) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Group) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Group) GetFaculty() Faculty {
	if m != nil {
		return m.Faculty
	}
	return Faculty_faculty_none
}

func (m *Group) GetStartYear() int64 {
	if m != nil {
		return m.StartYear
	}
	return 0
}

func (m *Group) GetTrainingDirection() int64 {
	if m != nil {
		return m.TrainingDirection
	}
	return 0
}

type User struct {
	Id              int64    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	FirstName       string   `protobuf:"bytes,2,opt,name=first_name,json=firstName" json:"first_name,omitempty"`
	LastName        string   `protobuf:"bytes,3,opt,name=last_name,json=lastName" json:"last_name,omitempty"`
	Sex             Sex      `protobuf:"varint,4,opt,name=sex,enum=models.Sex" json:"sex,omitempty"`
	GroupId         int64    `protobuf:"varint,5,opt,name=group_id,json=groupId" json:"group_id,omitempty"`
	Images          []*Image `protobuf:"bytes,6,rep,name=images" json:"images,omitempty"`
	MessagesFromAll bool     `protobuf:"varint,7,opt,name=messages_from_all,json=messagesFromAll" json:"messages_from_all,omitempty"`
	Bio             string   `protobuf:"bytes,8,opt,name=bio" json:"bio,omitempty"`
	Rating          int64    `protobuf:"varint,9,opt,name=rating" json:"rating,omitempty"`
	Age             int64    `protobuf:"varint,10,opt,name=age" json:"age,omitempty"`
	VkId            int64    `protobuf:"varint,11,opt,name=vk_id,json=vkId" json:"vk_id,omitempty"`
	// inject_tag: xorm:"jsonb notnull default '{}' 'created_at'"
	CreatedAt *google_protobuf1.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	AvatarUrl string                      `protobuf:"bytes,13,opt,name=avatar_url,json=avatarUrl" json:"avatar_url,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetSex() Sex {
	if m != nil {
		return m.Sex
	}
	return Sex_Woman
}

func (m *User) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *User) GetImages() []*Image {
	if m != nil {
		return m.Images
	}
	return nil
}

func (m *User) GetMessagesFromAll() bool {
	if m != nil {
		return m.MessagesFromAll
	}
	return false
}

func (m *User) GetBio() string {
	if m != nil {
		return m.Bio
	}
	return ""
}

func (m *User) GetRating() int64 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func (m *User) GetAge() int64 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *User) GetVkId() int64 {
	if m != nil {
		return m.VkId
	}
	return 0
}

func (m *User) GetCreatedAt() *google_protobuf1.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *User) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

type Image struct {
	Url         string `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	Color       string `protobuf:"bytes,2,opt,name=color" json:"color,omitempty"`
	Hash        string `protobuf:"bytes,3,opt,name=hash" json:"hash,omitempty"`
	HashVersion int64  `protobuf:"varint,4,opt,name=hash_version,json=hashVersion" json:"hash_version,omitempty"`
}

func (m *Image) Reset()                    { *m = Image{} }
func (m *Image) String() string            { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()               {}
func (*Image) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Image) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Image) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

func (m *Image) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Image) GetHashVersion() int64 {
	if m != nil {
		return m.HashVersion
	}
	return 0
}

type Dialog struct {
	// inject_tag: xorm:"unique index"
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *Dialog) Reset()                    { *m = Dialog{} }
func (m *Dialog) String() string            { return proto.CompactTextString(m) }
func (*Dialog) ProtoMessage()               {}
func (*Dialog) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Dialog) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Message struct {
	DialogId string `protobuf:"bytes,1,opt,name=dialog_id,json=dialogId" json:"dialog_id,omitempty"`
	Text     string `protobuf:"bytes,2,opt,name=text" json:"text,omitempty"`
	SenderId int64  `protobuf:"varint,3,opt,name=sender_id,json=senderId" json:"sender_id,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Message) GetDialogId() string {
	if m != nil {
		return m.DialogId
	}
	return ""
}

func (m *Message) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Message) GetSenderId() int64 {
	if m != nil {
		return m.SenderId
	}
	return 0
}

type Vote struct {
	// @inject_tag: storm:"index"
	TargetUserId int64 `protobuf:"varint,1,opt,name=target_user_id,json=targetUserId" json:"target_user_id,omitempty" storm:"index"`
	// @inject_tag: storm:"index"
	VoteType VoteType `protobuf:"varint,2,opt,name=vote_type,json=voteType,enum=models.VoteType" json:"vote_type,omitempty" storm:"index"`
	// @inject_tag: storm:"index"
	VoterId int64 `protobuf:"varint,3,opt,name=voter_id,json=voterId" json:"voter_id,omitempty" storm:"index"`
}

func (m *Vote) Reset()                    { *m = Vote{} }
func (m *Vote) String() string            { return proto.CompactTextString(m) }
func (*Vote) ProtoMessage()               {}
func (*Vote) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Vote) GetTargetUserId() int64 {
	if m != nil {
		return m.TargetUserId
	}
	return 0
}

func (m *Vote) GetVoteType() VoteType {
	if m != nil {
		return m.VoteType
	}
	return VoteType_vote_none
}

func (m *Vote) GetVoterId() int64 {
	if m != nil {
		return m.VoterId
	}
	return 0
}

type VkAuthRequest struct {
	VkToken string `protobuf:"bytes,1,opt,name=vk_token,json=vkToken" json:"vk_token,omitempty"`
}

func (m *VkAuthRequest) Reset()                    { *m = VkAuthRequest{} }
func (m *VkAuthRequest) String() string            { return proto.CompactTextString(m) }
func (*VkAuthRequest) ProtoMessage()               {}
func (*VkAuthRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *VkAuthRequest) GetVkToken() string {
	if m != nil {
		return m.VkToken
	}
	return ""
}

type VkAuthReply struct {
	User  *User  `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	Token string `protobuf:"bytes,3,opt,name=token" json:"token,omitempty"`
}

func (m *VkAuthReply) Reset()                    { *m = VkAuthReply{} }
func (m *VkAuthReply) String() string            { return proto.CompactTextString(m) }
func (*VkAuthReply) ProtoMessage()               {}
func (*VkAuthReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *VkAuthReply) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *VkAuthReply) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type UserRequest struct {
	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
}

func (m *UserRequest) Reset()                    { *m = UserRequest{} }
func (m *UserRequest) String() string            { return proto.CompactTextString(m) }
func (*UserRequest) ProtoMessage()               {}
func (*UserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *UserRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type UserReply struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *UserReply) Reset()                    { *m = UserReply{} }
func (m *UserReply) String() string            { return proto.CompactTextString(m) }
func (*UserReply) ProtoMessage()               {}
func (*UserReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *UserReply) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type RandomRequest struct {
	MinAge int64  `protobuf:"varint,1,opt,name=min_age,json=minAge" json:"min_age,omitempty"`
	MaxAge int64  `protobuf:"varint,2,opt,name=max_age,json=maxAge" json:"max_age,omitempty"`
	Sex    Sex    `protobuf:"varint,3,opt,name=sex,enum=models.Sex" json:"sex,omitempty"`
	Token  string `protobuf:"bytes,4,opt,name=token" json:"token,omitempty"`
}

func (m *RandomRequest) Reset()                    { *m = RandomRequest{} }
func (m *RandomRequest) String() string            { return proto.CompactTextString(m) }
func (*RandomRequest) ProtoMessage()               {}
func (*RandomRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *RandomRequest) GetMinAge() int64 {
	if m != nil {
		return m.MinAge
	}
	return 0
}

func (m *RandomRequest) GetMaxAge() int64 {
	if m != nil {
		return m.MaxAge
	}
	return 0
}

func (m *RandomRequest) GetSex() Sex {
	if m != nil {
		return m.Sex
	}
	return Sex_Woman
}

func (m *RandomRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type UsersReply struct {
	Users []*User `protobuf:"bytes,1,rep,name=users" json:"users,omitempty"`
}

func (m *UsersReply) Reset()                    { *m = UsersReply{} }
func (m *UsersReply) String() string            { return proto.CompactTextString(m) }
func (*UsersReply) ProtoMessage()               {}
func (*UsersReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *UsersReply) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type VoteRequest struct {
	UserId   int64    `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Token    string   `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
	VoteType VoteType `protobuf:"varint,3,opt,name=vote_type,json=voteType,enum=models.VoteType" json:"vote_type,omitempty"`
}

func (m *VoteRequest) Reset()                    { *m = VoteRequest{} }
func (m *VoteRequest) String() string            { return proto.CompactTextString(m) }
func (*VoteRequest) ProtoMessage()               {}
func (*VoteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *VoteRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *VoteRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *VoteRequest) GetVoteType() VoteType {
	if m != nil {
		return m.VoteType
	}
	return VoteType_vote_none
}

type VoteReply struct {
	Matched bool `protobuf:"varint,1,opt,name=matched" json:"matched,omitempty"`
}

func (m *VoteReply) Reset()                    { *m = VoteReply{} }
func (m *VoteReply) String() string            { return proto.CompactTextString(m) }
func (*VoteReply) ProtoMessage()               {}
func (*VoteReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *VoteReply) GetMatched() bool {
	if m != nil {
		return m.Matched
	}
	return false
}

func init() {
	proto.RegisterType((*TrainingDirection)(nil), "models.TrainingDirection")
	proto.RegisterType((*Group)(nil), "models.Group")
	proto.RegisterType((*User)(nil), "models.User")
	proto.RegisterType((*Image)(nil), "models.Image")
	proto.RegisterType((*Dialog)(nil), "models.Dialog")
	proto.RegisterType((*Message)(nil), "models.Message")
	proto.RegisterType((*Vote)(nil), "models.Vote")
	proto.RegisterType((*VkAuthRequest)(nil), "models.VkAuthRequest")
	proto.RegisterType((*VkAuthReply)(nil), "models.VkAuthReply")
	proto.RegisterType((*UserRequest)(nil), "models.UserRequest")
	proto.RegisterType((*UserReply)(nil), "models.UserReply")
	proto.RegisterType((*RandomRequest)(nil), "models.RandomRequest")
	proto.RegisterType((*UsersReply)(nil), "models.UsersReply")
	proto.RegisterType((*VoteRequest)(nil), "models.VoteRequest")
	proto.RegisterType((*VoteReply)(nil), "models.VoteReply")
	proto.RegisterEnum("models.Sex", Sex_name, Sex_value)
	proto.RegisterEnum("models.Faculty", Faculty_name, Faculty_value)
	proto.RegisterEnum("models.VoteType", VoteType_name, VoteType_value)
	proto.RegisterEnum("models.ObjectType", ObjectType_name, ObjectType_value)
	proto.RegisterEnum("models.ErrorCode", ErrorCode_name, ErrorCode_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Love service

type LoveClient interface {
	// Sends a greeting
	VkAuth(ctx context.Context, in *VkAuthRequest, opts ...grpc.CallOption) (*VkAuthReply, error)
	// User return user info by their id
	GetUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*User, error)
	// User return list of users
	RandomUsers(ctx context.Context, in *RandomRequest, opts ...grpc.CallOption) (*UsersReply, error)
	// Vote vote for user
	Vote(ctx context.Context, in *VoteRequest, opts ...grpc.CallOption) (*VoteReply, error)
}

type loveClient struct {
	cc *grpc.ClientConn
}

func NewLoveClient(cc *grpc.ClientConn) LoveClient {
	return &loveClient{cc}
}

func (c *loveClient) VkAuth(ctx context.Context, in *VkAuthRequest, opts ...grpc.CallOption) (*VkAuthReply, error) {
	out := new(VkAuthReply)
	err := grpc.Invoke(ctx, "/models.Love/VkAuth", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loveClient) GetUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := grpc.Invoke(ctx, "/models.Love/GetUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loveClient) RandomUsers(ctx context.Context, in *RandomRequest, opts ...grpc.CallOption) (*UsersReply, error) {
	out := new(UsersReply)
	err := grpc.Invoke(ctx, "/models.Love/RandomUsers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loveClient) Vote(ctx context.Context, in *VoteRequest, opts ...grpc.CallOption) (*VoteReply, error) {
	out := new(VoteReply)
	err := grpc.Invoke(ctx, "/models.Love/Vote", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Love service

type LoveServer interface {
	// Sends a greeting
	VkAuth(context.Context, *VkAuthRequest) (*VkAuthReply, error)
	// User return user info by their id
	GetUser(context.Context, *UserRequest) (*User, error)
	// User return list of users
	RandomUsers(context.Context, *RandomRequest) (*UsersReply, error)
	// Vote vote for user
	Vote(context.Context, *VoteRequest) (*VoteReply, error)
}

func RegisterLoveServer(s *grpc.Server, srv LoveServer) {
	s.RegisterService(&_Love_serviceDesc, srv)
}

func _Love_VkAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VkAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoveServer).VkAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.Love/VkAuth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoveServer).VkAuth(ctx, req.(*VkAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Love_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoveServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.Love/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoveServer).GetUser(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Love_RandomUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RandomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoveServer).RandomUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.Love/RandomUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoveServer).RandomUsers(ctx, req.(*RandomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Love_Vote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoveServer).Vote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.Love/Vote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoveServer).Vote(ctx, req.(*VoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Love_serviceDesc = grpc.ServiceDesc{
	ServiceName: "models.Love",
	HandlerType: (*LoveServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VkAuth",
			Handler:    _Love_VkAuth_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _Love_GetUser_Handler,
		},
		{
			MethodName: "RandomUsers",
			Handler:    _Love_RandomUsers_Handler,
		},
		{
			MethodName: "Vote",
			Handler:    _Love_Vote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "models.proto",
}

func init() { proto.RegisterFile("models.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1106 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x56, 0x4d, 0x6f, 0xdb, 0x46,
	0x13, 0x7e, 0x29, 0xea, 0x8b, 0x43, 0xc9, 0xa1, 0xd6, 0x6f, 0x1b, 0xda, 0x8d, 0x1b, 0x95, 0x48,
	0x0a, 0x55, 0x80, 0xa5, 0x54, 0x3d, 0xf5, 0x68, 0x34, 0x96, 0x2b, 0xa0, 0xb6, 0x0b, 0x46, 0x76,
	0x90, 0x13, 0xb1, 0x16, 0x57, 0x12, 0x2b, 0x92, 0xab, 0x2e, 0x97, 0x84, 0x84, 0xa2, 0x97, 0x1e,
	0x7b, 0x2a, 0xd0, 0x9f, 0x56, 0xf4, 0x1f, 0xf4, 0x87, 0x14, 0xfb, 0x41, 0x5b, 0x8a, 0x11, 0xa4,
	0x27, 0xcd, 0x3c, 0x33, 0x3b, 0x33, 0xcf, 0xee, 0xb3, 0x4b, 0x41, 0x2b, 0xa1, 0x21, 0x89, 0xb3,
	0xc1, 0x9a, 0x51, 0x4e, 0x51, 0x5d, 0x79, 0xc7, 0xcf, 0x16, 0x94, 0x2e, 0x62, 0x32, 0xc4, 0xeb,
	0x68, 0x88, 0xd3, 0x94, 0x72, 0xcc, 0x23, 0x9a, 0xea, 0xac, 0xe3, 0xe7, 0x3a, 0x2a, 0xbd, 0xbb,
	0x7c, 0x3e, 0xe4, 0x51, 0x42, 0x32, 0x8e, 0x93, 0xb5, 0x4a, 0xf0, 0x22, 0xe8, 0x4c, 0x19, 0x8e,
	0xd2, 0x28, 0x5d, 0xbc, 0x8e, 0x18, 0x99, 0x89, 0xc5, 0xe8, 0x00, 0x2a, 0x51, 0xe8, 0x1a, 0x5d,
	0xa3, 0x67, 0xfa, 0x95, 0x28, 0x44, 0xff, 0x87, 0x1a, 0x8f, 0x78, 0x4c, 0xdc, 0x4a, 0xd7, 0xe8,
	0x59, 0xbe, 0x72, 0xd0, 0x00, 0x0e, 0xb3, 0x25, 0x65, 0x3c, 0x48, 0x71, 0x42, 0x02, 0x4e, 0x92,
	0x75, 0x8c, 0x39, 0x71, 0x4d, 0x99, 0xd3, 0x91, 0xa1, 0x2b, 0x9c, 0x90, 0xa9, 0x0e, 0x78, 0x7f,
	0x18, 0x50, 0xbb, 0x60, 0x34, 0x5f, 0x3f, 0xaa, 0xff, 0x15, 0x34, 0xe6, 0x78, 0x96, 0xc7, 0x7c,
	0x2b, 0x3b, 0x1c, 0x8c, 0x9e, 0x0c, 0x34, 0xd7, 0xb1, 0x82, 0xfd, 0x32, 0x8e, 0x4e, 0x00, 0x32,
	0x8e, 0x19, 0x0f, 0xb6, 0x04, 0x33, 0xd9, 0xcb, 0xf4, 0x2d, 0x89, 0xbc, 0x23, 0x98, 0xa1, 0x53,
	0x40, 0x5c, 0xd3, 0x09, 0xc2, 0x92, 0x8f, 0x5b, 0x95, 0x69, 0x1d, 0xfe, 0x3e, 0x51, 0xef, 0x77,
	0x13, 0xaa, 0x37, 0x19, 0x61, 0x8f, 0x26, 0x3a, 0x01, 0x98, 0x47, 0x2c, 0x53, 0xdc, 0x34, 0x6d,
	0x4b, 0x22, 0x82, 0x12, 0xfa, 0x0c, 0xac, 0x18, 0x97, 0x51, 0x45, 0xb8, 0x29, 0x00, 0x19, 0x3c,
	0x01, 0x33, 0x23, 0x1b, 0xd9, 0xf4, 0x60, 0x64, 0x97, 0x4c, 0xde, 0x90, 0x8d, 0x2f, 0x70, 0x74,
	0x04, 0xcd, 0x85, 0xd8, 0x85, 0x20, 0x0a, 0xdd, 0x9a, 0x6c, 0xd8, 0x90, 0xfe, 0x24, 0x44, 0x2f,
	0xa1, 0x1e, 0x25, 0x78, 0x41, 0x32, 0xb7, 0xde, 0x35, 0x7b, 0xf6, 0xa8, 0x5d, 0x2e, 0x9e, 0x08,
	0xd4, 0xd7, 0x41, 0xd4, 0x87, 0x4e, 0x42, 0xb2, 0x4c, 0xd8, 0xc1, 0x9c, 0xd1, 0x24, 0xc0, 0x71,
	0xec, 0x36, 0xba, 0x46, 0xaf, 0xe9, 0x3f, 0x29, 0x03, 0x63, 0x46, 0x93, 0xb3, 0x38, 0x46, 0x0e,
	0x98, 0x77, 0x11, 0x75, 0x9b, 0x72, 0x46, 0x61, 0xa2, 0x4f, 0xa1, 0xce, 0x30, 0x8f, 0xd2, 0x85,
	0x6b, 0xc9, 0xee, 0xda, 0x13, 0x99, 0x78, 0x41, 0x5c, 0x90, 0xa0, 0x30, 0xd1, 0x21, 0xd4, 0x8a,
	0x95, 0x18, 0xd3, 0x96, 0x58, 0xb5, 0x58, 0x4d, 0x42, 0xf4, 0x2d, 0xc0, 0x8c, 0x11, 0xcc, 0x49,
	0x18, 0x60, 0xee, 0xb6, 0xba, 0x46, 0xcf, 0x1e, 0x1d, 0x0f, 0x94, 0xcc, 0x06, 0xa5, 0xcc, 0x06,
	0xd3, 0x52, 0x66, 0xbe, 0xa5, 0xb3, 0xcf, 0xb8, 0xd8, 0x54, 0x5c, 0x60, 0x8e, 0x59, 0x90, 0xb3,
	0xd8, 0x6d, 0xab, 0x4d, 0x55, 0xc8, 0x0d, 0x8b, 0xbd, 0x39, 0xd4, 0x24, 0x4f, 0x31, 0x89, 0x48,
	0x30, 0xd4, 0xcc, 0x39, 0x8b, 0x85, 0x00, 0x67, 0x34, 0xa6, 0xac, 0x14, 0xa0, 0x74, 0x10, 0x82,
	0xea, 0x12, 0x67, 0x4b, 0x7d, 0x00, 0xd2, 0x46, 0x5f, 0x40, 0x4b, 0xfc, 0x06, 0x05, 0x61, 0xd9,
	0xc3, 0xd1, 0xdb, 0x02, 0xbb, 0x55, 0x90, 0xe7, 0x42, 0xfd, 0x75, 0x84, 0x63, 0xba, 0xd8, 0x39,
	0x75, 0x4b, 0x9c, 0xba, 0xf7, 0x16, 0x1a, 0x97, 0x6a, 0xff, 0xc4, 0x09, 0x87, 0x32, 0x29, 0xb8,
	0xcf, 0x68, 0x2a, 0x60, 0x12, 0x8a, 0xc6, 0x9c, 0x6c, 0xb8, 0x9e, 0x46, 0xda, 0x62, 0x41, 0x46,
	0xd2, 0x90, 0x30, 0xb1, 0x40, 0xe9, 0xb2, 0xa9, 0x80, 0x49, 0xe8, 0x15, 0x50, 0xbd, 0xa5, 0x9c,
	0xa0, 0x17, 0x70, 0xc0, 0x31, 0x5b, 0x10, 0x1e, 0xe4, 0x99, 0xca, 0x54, 0x92, 0x6b, 0x29, 0x54,
	0x48, 0x71, 0x12, 0xa2, 0x53, 0xb0, 0x0a, 0xca, 0x49, 0xc0, 0xb7, 0x6b, 0xa2, 0x2f, 0x84, 0x53,
	0x2a, 0x41, 0x94, 0x99, 0x6e, 0xd7, 0xc4, 0x6f, 0x16, 0xda, 0x12, 0x82, 0x12, 0xf6, 0x4e, 0xe3,
	0x86, 0xf4, 0x27, 0xa1, 0xd7, 0x87, 0xf6, 0xed, 0xea, 0x2c, 0xe7, 0x4b, 0x9f, 0xfc, 0x9c, 0x93,
	0x8c, 0xcb, 0xdc, 0x55, 0xc0, 0xe9, 0x8a, 0xa4, 0x9a, 0x55, 0xa3, 0x58, 0x4d, 0x85, 0xeb, 0x9d,
	0x83, 0x5d, 0xe6, 0xae, 0xe3, 0x2d, 0xea, 0x42, 0x55, 0xcc, 0x28, 0xb3, 0xec, 0x51, 0xab, 0xec,
	0x2f, 0x46, 0xf4, 0x65, 0x44, 0xbe, 0x0a, 0xb2, 0x90, 0xa9, 0x5f, 0x05, 0x59, 0xe6, 0x4b, 0xb0,
	0x65, 0x8e, 0x6e, 0xf8, 0x14, 0x1a, 0xfb, 0x54, 0xeb, 0xb9, 0x24, 0xe9, 0x9d, 0x82, 0xa5, 0xf2,
	0xfe, 0x53, 0x33, 0xaf, 0x80, 0xb6, 0x8f, 0xd3, 0x90, 0x26, 0x3b, 0x85, 0x93, 0x28, 0x0d, 0x84,
	0x64, 0x75, 0xe1, 0x24, 0x4a, 0xcf, 0x16, 0x44, 0x06, 0xf0, 0x46, 0x06, 0x2a, 0x3a, 0x80, 0x37,
	0x22, 0xa0, 0xef, 0xa5, 0xf9, 0x81, 0x7b, 0x79, 0x4f, 0xa7, 0xba, 0x4b, 0xe7, 0x15, 0x80, 0x98,
	0x22, 0x53, 0x73, 0x7a, 0x50, 0x13, 0xd3, 0x64, 0xae, 0x21, 0xef, 0xe7, 0xfe, 0xa0, 0x2a, 0xe4,
	0xad, 0xc0, 0x16, 0x87, 0xf4, 0xb1, 0x0d, 0x78, 0xe8, 0x57, 0xd9, 0xe9, 0xb7, 0x7f, 0xf6, 0xe6,
	0xc7, 0xce, 0xde, 0x7b, 0x09, 0x96, 0x6a, 0x26, 0xa6, 0x73, 0x05, 0x73, 0x3e, 0x5b, 0x12, 0xd5,
	0xaa, 0xe9, 0x97, 0x6e, 0xff, 0x08, 0xcc, 0x37, 0x64, 0x83, 0x2c, 0xa8, 0xbd, 0xa5, 0x09, 0x4e,
	0x9d, 0xff, 0xa1, 0x06, 0x98, 0x97, 0x38, 0x75, 0x8c, 0xfe, 0x35, 0x34, 0xf4, 0x23, 0x8b, 0x1c,
	0x68, 0xe9, 0x67, 0x36, 0x48, 0x69, 0x4a, 0x54, 0xd6, 0xf8, 0x72, 0xec, 0x18, 0xc2, 0x38, 0xbf,
	0x18, 0x3b, 0x15, 0x89, 0x4c, 0x7e, 0x74, 0x4c, 0x54, 0x87, 0xca, 0x78, 0xec, 0x54, 0x05, 0xf0,
	0xfd, 0xc5, 0xd8, 0xa9, 0x49, 0xe0, 0xc6, 0xa9, 0xf7, 0x5f, 0x41, 0xb3, 0x1c, 0x14, 0xb5, 0x35,
	0x1b, 0x5d, 0xce, 0x86, 0x46, 0x18, 0x65, 0x71, 0xb4, 0x22, 0x8e, 0x81, 0x9a, 0x50, 0x95, 0x56,
	0xa5, 0x7f, 0x0d, 0x70, 0x7d, 0xf7, 0x13, 0x99, 0x71, 0xb9, 0xe6, 0xa0, 0xf4, 0xae, 0xd4, 0xa2,
	0x7b, 0x5f, 0x6c, 0xb2, 0x63, 0x3c, 0xf8, 0xa2, 0x8b, 0x53, 0x41, 0x1d, 0x68, 0x2b, 0x5f, 0x5f,
	0x5d, 0xc7, 0xec, 0xf7, 0xc0, 0x3a, 0x67, 0x8c, 0xb2, 0xef, 0x68, 0x28, 0x67, 0x90, 0x8e, 0x2e,
	0xd7, 0x82, 0xe6, 0x15, 0xe5, 0x63, 0x9a, 0xa7, 0xa1, 0x63, 0x8c, 0xfe, 0xae, 0x40, 0xf5, 0x07,
	0x5a, 0x10, 0x74, 0x09, 0x75, 0xa5, 0x7e, 0xf4, 0xc9, 0xfd, 0x76, 0xef, 0xde, 0x9c, 0xe3, 0xc3,
	0xf7, 0xe1, 0x75, 0xbc, 0xf5, 0x9e, 0xfe, 0xf6, 0xd7, 0x3f, 0x7f, 0x56, 0x3a, 0xe8, 0x89, 0xfc,
	0xfc, 0x16, 0x5f, 0x0f, 0x71, 0xce, 0x97, 0xc3, 0x62, 0x85, 0x2e, 0xa1, 0x71, 0xa1, 0xee, 0x33,
	0x3a, 0xdc, 0x13, 0x89, 0xae, 0xb6, 0xa7, 0x1c, 0xef, 0xb9, 0x2c, 0x73, 0x84, 0x9e, 0x96, 0x65,
	0xa4, 0x92, 0x86, 0xbf, 0x68, 0xe1, 0xfc, 0x8a, 0xde, 0x81, 0xad, 0xd4, 0x2f, 0xb5, 0xf8, 0x30,
	0xe2, 0xde, 0x95, 0x38, 0x46, 0xbb, 0x45, 0x95, 0x62, 0x1f, 0x97, 0x2e, 0xa8, 0x78, 0xed, 0xc5,
	0x1f, 0x82, 0x79, 0x14, 0x93, 0x0c, 0x4d, 0xf5, 0xd3, 0x74, 0xb8, 0xab, 0xb2, 0xb2, 0x62, 0x67,
	0x1f, 0x14, 0x05, 0x5f, 0xc8, 0x82, 0x9f, 0x7b, 0xcf, 0x3e, 0x30, 0xab, 0x68, 0x40, 0xee, 0xea,
	0xf2, 0x4b, 0xf0, 0xcd, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x3e, 0xf2, 0xe5, 0x8c, 0xb4, 0x08,
	0x00, 0x00,
}
